---
# add Mysql-Python support based on the OS
 - name: Add Python MySQL support on Debian/Ubuntu
   apt: pkg="python-mysqldb" state=present
   when: ansible_os_family == 'Debian'

 - name: Add Python MySQL support on RHEL/Centos
   yum: pkg="MySQL-python.x86_64" state=present
   when: ansible_os_family == 'RedHat'

 
# We access the db with the default anonymous user and then we set the root account 
# - name: Setting the root password
#   mysql_user: login_user=root  login_password= password="{{ root_password }}" user=root host=localhost  

# We import the my.cnf file to the remote db with our client credentials
 - name: Add root my.cnf
   copy: 
    src: my.cnf 
    dest: /root/.my.cnf
    owner: root
    group: root
    mode: 644

#from here on same as mysql_secure_installation disable test databases delete anon account and allow root access to the db only from  our localhost you will be able to access the db with sudo my sql -u -p 
 - name: Delete anonymous MySQL server user
   mysql_user:  user="" state=absent host=localhost

 - name: Remove test database
   mysql_db:  db=test state=absent

 - name: Secure the root user for IPV6 localhost (::1)
   mysql_user:  user=root password="{{ root_password }}" host="::1"

 - name: Secure the root user for  IPV4 localhost (127.0.0.1)
   mysql_user:  user=root password="{{ root_password }}" host="127.0.0.1"

 - name: Secure the root user for localhost domain
   mysql_user:  user=root password="{{ root_password }}" host="localhost"

 - name: Secure the root user for server_hostname domain 
   mysql_user:  user=root password="{{ root_password }}" host="{{ ansible_fqdn }}"

 